### ISSUE TITLE
Add hexd

### ISSUE THREAD

**Issue by yordis** [manewitz/hex-alfred#1]
- Add `hexd` to go to https://hexdocs.pm/

**Comment by manewitz** [comment]
@yordis about to push an update that adds this

**Comment by manewitz** [comment]
@yordis Pushed! The keyword is configurable, but I went with `hd` as default.

I don't think the official gallery is automatically pulling updates in but you can download the workflow directly here:

https://github.com/manewitz/hex-alfred/releases/tag/v2.5
