### ISSUE TITLE
Version 2.5 does not have a Bundle ID

### ISSUE THREAD

**Issue by vitorgalvao** [manewitz/hex-alfred#2]
[That is necessary](https://www.alfredforum.com/topic/20442-hexpm-search-for-elixir-packages/#comment-108964) for it to be updated in the Gallery.

**Comment by vitorgalvao** [comment]
@manewitz Without this fix, the updated version cannot go in the Gallery.

**Comment by manewitz** [comment]
@vitorgalvao thank you! latest release is pushed with correct bundle id.
https://github.com/manewitz/hex-alfred/releases/tag/v2.6

**Comment by vitorgalvao** [comment]
Thank you. Will be live soon.
